In [1]:
from scipy import stats
import random
import numpy as np
import pandas as pd

In [2]:
values = [1.0, 1.0, 2.0, 1.5, 3.0]

In [3]:
xs = []
for i in range(0,10):
    xs.append(random.randint(0,6))
    
xs

[3, 2, 5, 6, 1, 2, 1, 1, 2, 5]

In [4]:
ys = []
for i in range(0,10):
    ys.append(random.randint(0,4))
    
ys

[3, 4, 1, 4, 2, 3, 4, 4, 1, 4]

In [5]:
vs = []
for i in range(0,10):
    vs.append(random.uniform(0,4))
    
vs

[0.2868557186932845,
 1.3779293523411682,
 3.154259494972278,
 3.48724250121733,
 2.3698401527128956,
 0.07432116687732737,
 0.22105636415883145,
 1.713333839826701,
 1.7603785402228471,
 2.3948518042256413]

In [6]:
d = {'x':xs,'y':ys,'values':vs}

In [7]:
df = pd.DataFrame(d)
df

x  y    values
0  3  3  0.286856
1  2  4  1.377929
2  5  1  3.154259
3  6  4  3.487243
4  1  2  2.369840
5  2  3  0.074321
6  1  4  0.221056
7  1  4  1.713334
8  2  1  1.760379
9  5  4  2.394852

In [8]:
binx = [0,1,2,3,4,5,6]

biny = [0,1,2,3,4]

In [9]:
ret = stats.binned_statistic_2d(xs,ys,vs,'count',bins=[3,2])

In [10]:
ret

BinnedStatistic2dResult(statistic=array([[2., 4.],
       [0., 1.],
       [1., 2.]]), x_edge=array([1.        , 2.66666667, 4.33333333, 6.        ]), y_edge=array([1. , 2.5, 4. ]), binnumber=array([10,  6, 13, 14,  5,  6,  6,  6,  5, 14], dtype=int64))

In [11]:
ret.statistic

array([[2., 4.],
       [0., 1.],
       [1., 2.]])

In [12]:
ret.x_edge

array([1.        , 2.66666667, 4.33333333, 6.        ])

In [13]:
ret.y_edge

array([1. , 2.5, 4. ])